//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RateLimitWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment_Tbl
    {
        public int CommentId { get; set; }
        public int ArticalId { get; set; }
        public System.Guid GuestId { get; set; }
        public string CommentDescription { get; set; }
        public int Rating { get; set; }
        public System.DateTime CommentOn { get; set; }
    
        public virtual Artical_Tbl Artical_Tbl { get; set; }
    }
}
